version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todolist-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todolist_net

  web:
    build: .
    container_name: todolist-web
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - todolist_net

volumes:
  pgdata:

networks:
  todolist_net:
