site_name: TodoList
site_url: https://iancostag.github.io/todolist-RoR/

repo_url: https://github.com/iancostag/todolist-RoR
repo_name: GitHub

theme:
  name: material

nav:
  - Descrição do Desafio e Introdução ao Negócio: index.md
  - Requisitos: paginas/requisitos.md
  - Técnicas de Engenharia de Requisitos Aplicadas: paginas/er.md
  - Backlog: paginas/backlog.md
  - Modelagem do Banco de Dados: paginas/modelagem.md